name: Convert Markdown to PDF

on:
  push:
    paths:
      - "*.md"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-xetex -y

      - name: Convert Markdown to PDF
        run: |
          pandoc ProjectDescription.md -o ProjectDescription.pdf --pdf-engine=xelatex
          
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: converted-pdf
          path: ProjectDescription.pdf
